### ISSUE TITLE
Add @prisma/internals as dependency

### ISSUE THREAD

**Issue by jorgenskogas** [morgothulhu/nexus-plugin-prisma#7]
Add @prisma/internals from devDependencies to dependencies

```
Error: "Cannot find module '@prisma/internals'\nRequire stack:\n- /private/var/folders/gc/kk64y5156mv3t_m45my46_t80000gn/T/tmp1667541690397_20ba02cb-d58d-4ada-abec-24054d06742d.js"
    at /path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/utilsSync.ts:73:24
    at transform (/path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/dmmf/transformer.ts:92:32)
    at getTransformedDmmf (/path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/dmmf/transformer.ts:31:5)
    at new SchemaBuilder (/path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/builder.ts:250:25)
    at build (/path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/builder.ts:168:19)
    at Object.onInstall (/path-to-monorepo/node_modules/@morgothulhu/nexus-plugin-prisma/src/plugin.ts:46:83)
    at /path-to-monorepo/node_modules/nexus/src/builder.ts:650:44
    at Array.forEach (<anonymous>)
    at SchemaBuilder.beforeWalkTypes (/path-to-monorepo/node_modules/nexus/src/builder.ts:643:18)
    at SchemaBuilder.getFinalTypeMap (/path-to-monorepo/node_modules/nexus/src/builder.ts:802:10
```

**Comment by morgothulhu** [comment]
got it. added in `0.43.6`
